#!/bin/bash

# conf
./ssh/init
./hypr/init
./kitty/init
./wofi/init
./waybar/init
./nvim/init
./zsh/init
./yazi/init
./fcitx5/init

# bin
sudo ln -sf ~/_dotfile/bin/flash51 /bin/flash51

# skel
./skel

# variable

ln -sf ~/_dotfile/wallpapers/wallpapers/Manga-Girl-Rain.png ~/.current_wallpaper
ln -sf ~/_dotfile/avatar.png ~/.current_avatar
