#!/bin/bash

# conf
./ssh/init
./hypr/init
./kitty/init
./wofi/init
./waybar/init
./nvim/init
./zsh/init
./yazi/init
./fcitx/init

# bin
sudo ln -sf ~/_dotfile/bin/flash51 /bin/flash51

# skel
./skel
